#!/bin/bash
# compile_env.sh
# Scans the local system for modern CLI tools and aliases, and writes them to the global Environment profile.

ENV_FILE="$HOME/Library/CloudStorage/Dropbox/agents/config/ENVIRONMENT.md"
echo "# Environment Profile" > "$ENV_FILE"
echo "> Auto-generated by compile_env.sh" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

echo "## Core Tools & Replacements" >> "$ENV_FILE"
echo "Always use these commands if they are available instead of the POSIX defaults:" >> "$ENV_FILE"

# Check for modern replacements
if command -v trash &> /dev/null || alias trash &> /dev/null; then
    echo "- **Safe Delete**: Use \`trash\` instead of \`rm\` to prevent accidental permanent deletion." >> "$ENV_FILE"
else
    echo "- **Safe Delete**: \`trash-cli\` not found. Use \`rm\` carefully." >> "$ENV_FILE"
fi

if command -v rg &> /dev/null; then
    echo "- **Search**: Use \`rg\` (ripgrep) instead of \`grep\` for faster searching." >> "$ENV_FILE"
fi

if command -v fd &> /dev/null; then
    echo "- **Find**: Use \`fd\` instead of \`find\` for faster directory traversal." >> "$ENV_FILE"
fi

if command -v bat &> /dev/null; then
    echo "- **Read**: Use \`bat\` instead of \`cat\` for syntax-highlighted output." >> "$ENV_FILE"
fi

if command -v eza &> /dev/null; then
    echo "- **List**: Use \`eza\` instead of \`ls\`." >> "$ENV_FILE"
fi

echo "" >> "$ENV_FILE"
echo "## Installed Global Packages" >> "$ENV_FILE"
echo "A quick snapshot of global dependencies to prevent the agent from needing to query them." >> "$ENV_FILE"

echo "### NPM Globals" >> "$ENV_FILE"
echo "\`\`\`text" >> "$ENV_FILE"
if command -v npm &> /dev/null; then
    npm list -g --depth=0 2>/dev/null | sed '1d' | sed 's/^[├└]─[─]* //g' | awk '{print "- "$1}' >> "$ENV_FILE" || echo "Error reading npm list" >> "$ENV_FILE"
else
    echo "npm not installed" >> "$ENV_FILE"
fi
echo "\`\`\`" >> "$ENV_FILE"

echo "### Homebrew Packages (Top Level)" >> "$ENV_FILE"
echo "\`\`\`text" >> "$ENV_FILE"
if command -v brew &> /dev/null; then
    brew leaves 2>/dev/null | awk '{print "- "$1}' >> "$ENV_FILE" || echo "Error reading brew leaves" >> "$ENV_FILE"
else
    echo "brew not installed" >> "$ENV_FILE"
fi
echo "\`\`\`" >> "$ENV_FILE"

echo -e "\nEnvironment profile compiled to $ENV_FILE"
